# ===================================================================
# APPLICATION SPRING BOOT : locataire-rest-api
# ===================================================================
spring.application.name=locataire-rest-api
server.port=8182

# ===================================================================
# BASE DE DONNÉES (PostgreSQL)
# ===================================================================
# Axon va automatiquement y créer une table 'token_entry'
spring.datasource.url=jdbc:postgresql://localhost:5432/tenancydb?sslmode=disable
spring.datasource.username=ddrissa
spring.datasource.password=dddd
spring.jpa.hibernate.ddl-auto=update

# Configuration de JPA/Hibernate

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===================================================================
# CONFIGURATION AXON FRAMEWORK 4.13.0
# ===================================================================
axon.axonserver.enabled=true
axon.axonserver.servers=localhost:8124
axon.axonserver.context=default
axon.axonserver.component-name=${spring.application.name}

# --- Sérialisation JSON ---
axon.serializer.events=jackson
axon.serializer.messages=jackson
axon.serializer.general=jackson
spring.jackson.serialization.write-dates-as-timestamps=false


# ===================================================================
# CONFIGURATION DES PROCESSEURS D'ÉVÉNEMENTS (Mode Tracking)
# ===================================================================
# Le "Processing Group" par défaut est le nom du package de vos @Component contenant des @EventHandler.
# Supposons que vos classes de projection soient dans le package : com.example.tenancyservice.projection
#Mais pour plus de clarté, on peut les regrouper dans un "Processing Group" nommé "tenancy-projections" 
#(ou un autre nom significatif).

# On configure ce groupe pour qu'il lise depuis Axon Server (l'Event Store)
#axon.eventhandling.processors.tenancy-projections.source=axonServerEventStore
# On force le mode "tracking" (sauvegarde du token en base de données)
#axon.eventhandling.processors.tenancy-projections.mode=tracking

# (Optionnel) Optimisation : Traitement parallèle
# Segment-count définit en combien de "morceaux" le flux est divisé.
# Configuration vitale pour que le service mette à jour ses projections asynchronement
#axon.eventhandling.processors.tenancy-projections.source=axonServerEventStore
axon.eventhandling.processors.tenancy-projections.mode=tracking

# ===================================================================
# CONFIGURATION SWAGGER (OpenAPI) POUR LA DOCUMENTATION DES API REST
# ===================================================================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
