spring.application.name=raiting-service
server.port=8183
# Configuration de la base de données PostgreSQL pour Notationdb
spring.datasource.url=jdbc:postgresql://localhost:5432/notationdb
spring.datasource.username=ddrissa
spring.datasource.password=dddd
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ------ CONFIGURATION AXON FRAMEWORK ------
# Configuration du serveur Axon
axon.axonserver.servers=localhost:8124
# --- GROUPE 2 : DONNÉES DE RÉFÉRENCE (Le cache local) ---
# Correspond à la classe annotée avec @ProcessingGroup("query-finance-reference-data")
# (ex: ReferenceDataProjection)
axon.eventhandling.processors.raiting-projections.source=axonServerEventStore
axon.eventhandling.processors.raiting-projections.mode=tracking
# Pas besoin d'optimisation poussée (segments/threads multiples) pour ce groupe, 
# car la création de locataires/biens est un événement rare par rapport aux paiements.

 #--- SWAGGER CONFIGURATION ---
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs