spring.application.name=immobilier-rest-api
server.port=8181

# ===================================================================
# BASE DE DONNÉES (PostgreSQL)
# ===================================================================

# Configuration de la base de données PostgreSQL pour Immobilierdb
spring.datasource.url=jdbc:postgresql://localhost:5432/immobilierdb?sslmode=disable
spring.datasource.username=ddrissa
spring.datasource.password=dddd
spring.jpa.hibernate.ddl-auto=update

# Configuration de JPA/Hibernate

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===================================================================
# CONFIGURATION AXON FRAMEWORK 4.13.0
# ===================================================================
axon.axonserver.enabled=true
axon.axonserver.servers=localhost:8124

# Contexte partagé
axon.axonserver.context=default
# Identifiant unique de l'application dans Axon Server
axon.axonserver.component-name=${spring.application.name}

# --- Sérialisation JSON (Crucial pour les microservices) ---
axon.serializer.events=jackson
axon.serializer.messages=jackson
axon.serializer.general=jackson
spring.jackson.serialization.write-dates-as-timestamps=false

# ===================================================================
# CONFIGURATION SWAGGER (OpenAPI) POUR LA DOCUMENTATION DES API REST
# ===================================================================

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs



