spring.application.name=tenancy-query-service

server.port=8187
#`Activer les threads virtuels pour une meilleure performance avec Axon Server
spring.threads.virtual.enabled=true

# 1. Connexion MongoDB
spring.data.mongodb.uri=mongodb://ddrissa:dddd@localhost:27017/tenancy_query_db?authSource=admin

# 2. Axon Server
axon.axonserver.enabled=true
axon.axonserver.servers=localhost:8124
axon.axonserver.context=default
axon.axonserver.component-name=${spring.application.name}

# 3. Sérialisation JSON
axon.serializer.events=jackson
axon.serializer.messages=jackson
axon.serializer.general=jackson
spring.jackson.serialization.write-dates-as-timestamps=false

# 4. Axon Mongo Extension (OBLIGATOIRE pour les Tracking Processors avec Mongo)
axon.mongo.token-store.enabled=true
axon.mongo.saga-store.enabled=false
axon.mongo.event-store.enabled=false

# 5. Configuration du Processing Group
#axon.eventhandling.processors.tenancy-views.source=axonServerEventStore
axon.eventhandling.processors.tenancy-views.mode=tracking


# ===================================================================
# CONFIGURATION SWAGGER (OpenAPI) POUR LA DOCUMENTATION DES API REST
# ===================================================================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
# Trier les endpoints par ordre alphabétique au lieu de l'ordre d'apparition dans le code
springdoc.swagger-ui.operationsSorter=alpha
# Indiquer à Springdoc de ne scanner QUE le package de vos contrôleurs REST
# (très utile pour éviter que Swagger documente des contrôleurs internes de Spring Boot)
springdoc.packagesToScan=ci.kossovo.tenancy_query_service.api
